function rollNum() {
    var number = Math.random()*(7-1) + 1;
    document.getElementById("number--display__appear").innerHTML = Math.floor(number);
}

let wordSelection = [
    "new",
    "good",
    "first",
    "last",
    "long",
    "great",
    "little",
    "own",
    "other",
    "old",
    "right",
    "big",
    "high",
    "different",
    "small",
    "large",
    "next",
    "early",
    "young",
    "important",
    "few",
    "public",
    "bad",
    "able",
    "general",
    "specific",
    "certain",
    "free",
    "open",
    "whole",
    "short",
    "easy",
    "strong",
    "special",
    "clear",
    "recent",
    "late",
    "single",
    "medical",
    "central",
    "common",
    "poor",
    "major",
    "happy",
    "serious",
    "ready",
    "environmental",
    "financial",
    "blue",
    "federal",
    "necessary",
    "military",
    "original",
    "successful",
    "sufficient",
    "electrical",
    "expensive",
    "academic",
    "aware",
    "additional",
    "available",
    "comfortable",
    "traditional",
    "cultural",
    "primary",
    "professional",
    "international",
    "useful",
    "historical",
    "effective"
     

];

function wordClickBox() {
    document.getElementById("word--display__appear").innerHTML= wordSelection[Math.floor(Math.random()* wordSelection.length)];
}